---
 - hosts: centvm
   remote_user: ansible
   become: true
   tasks:
           - name: install httpd
             yum:
                     name: httpd
                     state: installed
             register: install
             ignore_errors: true
           - debug:
                     msg: "installation failed"
             when: install.failed == true        
           - name: restart service
             service:
                     name: httpd
                     state: started
             register: service
             ignore_errors: true
           - debug:
                     msg: "service failed"
             when: service.failed == true
           - debug:
                     msg: "Playbook was Unsuccessful"
             when: install.failed == true and service.failed == true       
                        
