---
 - hosts: centvm
   remote_user: ansible
   become: true
   tasks:
           - name: date
             copy: 
                    content: "current hostname is {{ ansible_hostname }}\nprocessor count is {{ansible_processor_count}}\ncurrent bios version is {{ ansible_bios_version }}\ncurrent ipv4 address is {{ ansible_all_ipv4_addresses }}\ncurrent mac address is {{ ansible_default_ipv4.macaddress }}"
                    dest: /home/ansible/info.txt     
                 
