---
 - hosts: fedvm
   remote_user: ansible
   become: true
   tasks:
           - name: httpinstall
             yum:
                     name: httpd
                     state: installed
             tags: install        
           - name: adding content to http
             copy:
                     content: "hello from {{ ansible_hostname }}"
                     dest: /var/www/html/index.html
           - name: restarting the http
             service:
                     name: httpd
                     state: restarted

                      
