---
 - hosts: centvm
   remote_user: ansuser
   become: true
   tasks:
           - name: check if /dev/data volume group exist
             debug:
                     msg: "VG present"
             register: present
             when: ansible_lvm.vgs.data is defined
           - name: check if /dev/data volume group not exist
             debug:
                     msg: "VG absent"
             when: ansible_lvm.vgs.data is not defined
           - name: Create a logical volume of 2GB
             lvol:
                      vg: data
                      lv: mylv
                      size: 2G
             register: lv
             ignore_errors: true
             when: ansible_lvm.vgs.data is defined 
           - name: when 2GB failed create a lv with 800MB              
             lvol:
                      vg: data
                      lv: mylv
                      size: 800M
                      force: yes
             register: vg         
             when: ansible_lvm.vgs.data is defined and lv.failed == true
             ignore_errors: true        
           - name: format the lv
             filesystem:
                     fstype: ext4
                     dev: /dev/data/mylv
             when: ansible_lvm.vgs.data is defined          
           - name: creating a mountpoint
             file:
                      path: /data
                      state: directory
             when: ansible_lvm.vgs.data is defined        
           - name: mounting the lvm
             mount:
                       fstype: ext4
                       src: /dev/data/mylv
                       path: /data
                       state: mounted
             when:  ansible_lvm.vgs.data is defined
           - name: playbook fail
             debug:
                     msg: "PLAYBOOK FAILED"
             when: ansible_lvm.vgs.data is not defined        
